### ISSUE TITLE
Have you tested on mesh reconstruction?

### ISSUE THREAD

**Issue by ForrestPi** [samholt/NeuralLaplace#5]
Hi, have you tested on mesh reconstruction?

**Comment by samholt** [comment]
Hi @ForrestPi 

To understand your question in more detail, could you elaborate what you mean with a specific example? And or provide references to papers that tackle this problem?

The examples in this repo reconstruct future values of a trajectory for 1D and 2D examples, on a uniformly spaced time point grid.

Keen to understand more to help better,

All the best,
Sam
