### ISSUE TITLE
How to use Neural Laplace?

### ISSUE THREAD

**Issue by qm-intel** [samholt/NeuralLaplace#8]
@samholt Thanks for your great contribution. I am wondering how to use the Laplace Transform and ILT for the 2D data

**Comment by samholt** [comment]
Hi @qm-intel

Thank you for your question and interest in using this package.

Sadly, this package currently only implements the Laplace Transform and ILT for 1D signals and treats multiple dimensions independently, performing the 1D LT or ILT on them separately.

You could adapt the existing Laplace Transform and ILT algorithms to be N-dimensional for use with 2D and 3D data/images, and I welcome any contribution. However, this is not currently implemented.

If you have any further questions, do let me know.

All the best,
Sam

**Comment by qm-intel** [comment]
@samholt Can you please explain more about where should I start?
